### ISSUE TITLE
1.4.1 does not work with the Oculus Rift

### ISSUE THREAD

**Issue by Bamux** [mischiminator/RumbleEnhancer#4]
The latest version does not work with the Oculus Rift. I can change the rumble strength in the Beat Saber menu but it has no effect. The last version where it still worked for me was 1.2.0.

**Comment by mischiminator** [comment]
Fixed in 1.4.2
i messed something in the calculation

**Comment by Bamux** [comment]
In my Userdata folder I now see a Enhancer.json with 1.4.2. But the problem still exists. No matter which RumbleStrength I set it has no effect.

```
{
  "RegenerateConfig": false,
  "plugin_name": "RumbleEnhancer",
  "RumbleStrength": 1,
  "RumbleTimeMS": 25,
  "TimeBetweenRumblePulsesMS": 5
}
```

**Comment by mischiminator** [comment]
Try setting it to 10 and maybe send log files

**Comment by Bamux** [comment]
10 is as strong as 1 even at 0 I get the same force feedback (Oculus Rift). The strange thing is that it worked with 1.2.0 before Beat Games updated the game. How do I get logfiles?

**Comment by Bamux** [comment]
latest log:
[INFO @ 18:30:56 | Rumble Enhancer] Plugin Version 1.4.2 loaded!
[INFO @ 18:31:03 | Rumble Enhancer] Settings attached!
[INFO @ 18:31:22 | Rumble Enhancer] Settings attached!
[INFO @ 18:31:30 | Rumble Enhancer] Settings attached!
[INFO @ 18:31:36 | Rumble Enhancer] Settings attached!
[INFO @ 18:31:40 | Rumble Enhancer] Plugin unloaded!

**Comment by Bamux** [comment]
entire log
[2019.04.30.18.30.log](https://github.com/mischiminator/RumbleEnhancer/files/3132178/2019.04.30.18.30.log)

**Comment by mischiminator** [comment]
This Plugin has its own log in the log dir of beat saber

**Comment by Bamux** [comment]
I posted the content from the Rumble Enhancer log:

```
[INFO @ 18:30:56 | Rumble Enhancer] Plugin Version 1.4.2 loaded!
[INFO @ 18:31:03 | Rumble Enhancer] Settings attached!
[INFO @ 18:31:22 | Rumble Enhancer] Settings attached!
[INFO @ 18:31:30 | Rumble Enhancer] Settings attached!
[INFO @ 18:31:36 | Rumble Enhancer] Settings attached!
[INFO @ 18:31:40 | Rumble Enhancer] Plugin unloaded!
```

Is it normal that the plugin is unloaded ? [INFO @ 18:31:40 | Rumble Enhancer] Plugin unloaded!

In the detailed log of Beatsaber you can see that it comes to problems:
[ERROR @ 18:30:57 | IPA/Updater] Error getting info for rumbleenhancer
[WARNING @ 18:30:58 | IPA/Updater] rumbleenhancer info request failed, not trying again.

I also tried a fresh installation and deleted all plugins and reinstalled only the Required Plugins with the latest [3.4.1 Beat Saber Mod Manager](https://github.com/beat-saber-modding-group/BeatSaberModInstaller/releases) without success. 
I have inserted afterwards manually your latest RumbleEnhancer.dll but again without success.

Does it work on your Oculus Rift ?
I'm playing with the Oculus Store version, maybe that's the reason that it's not working?

**Comment by Bamux** [comment]
Update: I have now tried another [RumbleEnhancer](https://github.com/Ibodan/RumbleEnhancerOculus) especially for Oculus which works for me, but it doesn't have an easy way to adjust the Rumble strength like with your plugin.
